apiVersion: v1
kind: Service
metadata:
  name: mcki-back
  labels:
    app: mcki
spec:
  selector: 
    app: mcki
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30500
  clusterIP: 10.4.0.2
  externalIPs:
    - 35.247.67.242
