apiVersion: v1
kind: Service
metadata:
  name: mcki-front
  labels:
    app: mcki
spec:
  selector: 
    app: mcki
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30600
  externalIPs:
    - 35.247.67.242
